
title: Meine Webseite
description: Willkommen auf meiner Webseite
baseurl: ""
url: "https://username.github.io" # Replace with your GitHub Pages URL
theme: minima

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom colors
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      background_color: "#f5f5dc" # Beige
      accent_color: "#ff9800"     # Orange
      text_color: "#6b4423"      # Erdton
